Studentportalen/urls.py
from django.conf.urls import url
from . import views

app_name = 'Studentportalen'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^emner/$', views.emner, name='emner'),
    url(r'^fag/+(?P<emne_id>[0-9]+)/$', views.fag, name='fag'),
    url(r'^logg_inn/$', views.login_view, name='login_user'),
    url(r'^logg_ut/$', views.logout_view, name='logout_user'),
    url(r'^registrering/$', views.register, name='registrering'),
]

Studentpotalen/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib import auth



urlpatterns = [
    url(r'^', include('Studentportalen.urls')),
    url(r'^admin/', admin.site.urls),
]

Studentportalen/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from .choices import *



class Emne(models.Model):
    navn = models.CharField(max_length=150)
    beskrivelse = models.CharField(max_length=300, default='Beskrivelse av faget')
    tags = models.CharField(max_length=100)
    vanskelig = models.FloatField(default=0)
    interesse = models.FloatField(default=0)
    arbeid = models.FloatField(default=0)
    info = models.TextField(max_length=1000)
    antall = models.IntegerField(default=0)

    def __str__(self):
        return self.navn


class Studie(models.Model):
    navn = models.CharField(max_length=100)
    rangering = models.FloatField()
    beskrivelse = models.TextField(max_length=1000)
    url = models.URLField(max_length=200)

    def __str__(self):
        return self.navn


class Vurdering(models.Model):
    emne = models.ForeignKey(Emne, default=1, on_delete=models.CASCADE)
    bruker = models.ForeignKey(User, default=1)
    tittel = models.CharField(default='Tittel', max_length=200)
    vanskelig = models.IntegerField(default=1, choices=VANSK_CHOICES)
    interesse = models.IntegerField(default=1, choices=INT_CHOICES)
    arbeid = models.IntegerField(default=1, choices=ARB_CHOICES)
    kommentar = models.TextField(max_length=2000)

    def __str__(self):
        return self.tittel

Studentportalen/forms.py
from django import forms
from django.forms import ModelForm
from .models import Vurdering, User
from .choices import *
from django.utils.translation import ugettext_lazy as _


class VurderingForm(ModelForm):

    vanskelig = forms.ChoiceField(choices=VANSK_CHOICES, label='Hvor vanskelig er dette faget?'
                                  , widget=forms.Select(
            attrs={
                'class': 'form-control',
            }
        ), required=True)
    interesse = forms.ChoiceField(choices=INT_CHOICES, label='Hvor interessant er dette faget?'
                                  , widget=forms.Select(
            attrs={
                'class': 'form-control'
            }
        ), required=True)
    arbeid = forms.ChoiceField(choices=ARB_CHOICES, label='Hvor mye arbeid krever dette faget?',
                               widget=forms.Select(
                                   attrs={
                                       'class': 'form-control'
                                   }
                               ), required=True)
    tittel = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Skriv en tittel..'
        }
    ), label='Skriv en tittel til din vurdering')

    kommentar = forms.CharField(label='Skriv din vurdering:', widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'Skriv din vurdering..'
        }
    ))

    class Meta:
        model = Vurdering
        fields = ['tittel', 'vanskelig', 'interesse', 'arbeid', 'kommentar']


class UserForm(forms.ModelForm):
    username = forms.CharField(label='Velg et brukernavn:', widget=forms.TextInput(
        attrs={
            'class': 'form-control'
        }
    ))
    email = forms.CharField(label='Din epost:', widget=forms.EmailInput(
        attrs={
            'class': 'form-control'
        }
    ))
    password = forms.CharField(label='Passord:', widget=forms.PasswordInput(
        attrs={
            'class': 'form-control'
        }
    ))
    password2 = forms.CharField(label='Gjenta passord:', widget=forms.PasswordInput(
        attrs={
            'class': 'form-control'
        }
    ))

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        labels = {
            'username': _('Brukernavn'),
            'email': _('Epost'),
            'password': _('Passord'),
        }
class LoginForm(forms.ModelForm):
    username = forms.CharField(label='Brukernavn', widget=forms.TextInput(
        attrs={
            'class': 'form-control'
        }
    ))

    password = forms.CharField(label='Passord:', widget=forms.PasswordInput(
        attrs={
            'class': 'form-control'
        }
    ))


    class Meta:
        model = User
        fields = ['username', 'password']

Studentportalen/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import Emne, Studie, Vurdering
from .forms import VurderingForm, UserForm, LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout


# Create your views here.


def index(request):
    emne_vansk = Emne.objects.order_by('-vanskelig')[:3]
    emne_arb = Emne.objects.order_by('-arbeid')[:3]
    emne_inte = Emne.objects.order_by('-interesse')[:3]
    emne_anta = Emne.objects.order_by('-antall')[:3]

    context = {'emn_vansk': emne_vansk, 'emne_arb': emne_arb, 'emne_inte': emne_inte, 'emne_anta': emne_anta}

    return render(request, 'Studentportalen/index_django.html', context)


def finnPoeng(emne):

    vurderinger = Vurdering.objects.filter(emne__exact=emne)

    teller, vansk, arb, inte = 0, 0, 0, 0

    for vurd in vurderinger:
        teller += 1
        vansk += vurd.vanskelig
        arb += vurd.arbeid
        inte += vurd.interesse

    if teller != 0:
        vansk, inte, arb = (vansk / teller), (inte / teller), (arb / teller)

    return vansk, inte, arb


def emner(request):
    emner = Emne.objects.all()

    return render(request, 'Studentportalen/emner_django.html', {'emner': emner})


def fag(request, emne_id):

    emne = get_object_or_404(Emne, pk=emne_id)
    vurderinger = Vurdering.objects.filter(emne__exact=emne)

    teller, vansk, arb, inte = 0, 0, 0, 0

    for vurd in vurderinger:
        teller += 1
        vansk += vurd.vanskelig
        arb += vurd.arbeid
        inte += vurd.interesse

    if teller != 0:
        vansk, inte, arb = (vansk/teller), (inte/teller), (arb/teller)

    width_vansk = int((100 / 5) * vansk)
    width_int = int((100 / 5) * inte)
    width_arb = int((100 / 5) * arb)
    vansk, inte, arb = round(vansk, 1), round(inte, 1), round(arb, 1)
    width = {'vansk': width_vansk, 'int': width_int, 'arb': width_arb}
    verdi = {'vansk': vansk, 'inte': inte, 'arb': arb}

    if request.method == 'POST':

        form = VurderingForm(request.POST or None)
        if form.is_valid():
            vurdering = form.save(commit=False)
            vurdering.bruker = request.user
            vurdering.emne = emne
            vurdering.save()
            vurderinger_2 = Vurdering.objects.filter(emne__exact=emne)
            emne_kalk(emne_id)
            return redirect(request.path_info)

        else:
            redirect(request.path_info)

    else:
        form = VurderingForm()

        return render(request, 'Studentportalen/fag_django.html', {'emne': emne, 'width': width, 'form': form,
                                                                   'verdi': verdi, 'vurderinger': vurderinger})


def emne_kalk(emne_id):
    emne = get_object_or_404(Emne, pk=emne_id)
    vurderinger = Vurdering.objects.filter(emne__exact=emne)

    teller, vansk, arb, inte = 0, 0, 0, 0

    for vurd in vurderinger:
        teller += 1
        vansk += vurd.vanskelig
        arb += vurd.arbeid
        inte += vurd.interesse

    if teller != 0:
        vansk, inte, arb = (vansk / teller), (inte / teller), (arb / teller)

    emne_antall = teller

    emne.vanskelig = round(vansk, 1)
    emne.interesse = round(inte, 1)
    emne.arbeid = round(arb, 1)
    emne.antall = emne_antall
    emne.save()


def login_view(request):
    form = LoginForm

    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("/")

        else:

            return render(request, 'Studentportalen/logg_inn.html', {'error_message': 'Invalid login'})
    else:
        return render(request, 'Studentportalen/logg_inn.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect("/")


def register(request):

    if request.method == 'POST':
        form = UserForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            password2 = form.cleaned_data['password2']
            if password == password2:

                user.set_password(password)
                user.save()
                user = authenticate(username=username, password=password)
                login(request, user)
                return redirect("/")

            else:
                return render(request, 'Studentportalen/registrering.html',
                              {'form': form, 'error_message': 'Passordene er ikke like'})
        else:
            return render(request, 'Studentportalen/registrering.html',
                          {'form': form, 'error_message': 'Brukernavnet er tatt'})

    else:
        form = UserForm()
        context = {
            "form": form,
        }
        return render(request, 'Studentportalen/registrering.html', context)

Studentportalen/templates/Studentportalen/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block head_title %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}" type="text/css">
    <link rel="icon" href="{% static 'bilder/LeLogo.png' %}" sizes="48x48" />
    <script src="{% static 'jquery-3.2.1.js' %}"></script>
    <script src="{% static 'main.js' %}"></script>
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="50" style="background-color: white; color: #4e4f51;">
<div class="container-fluid">

    <!-- NAVBAR START -->

    <nav class="navbar navbar-inverse navbar-toggleable-md opaque-navbar" id="navBar">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'Studentportalen:index' %}" id="navBrand1">
            <img src="{% static 'bilder/LeLogo.png' %}" style="width: 30px;height: 30px; margin-right: 30px">
        </a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                 <li class="nav-item {% if request.path == '/' %} active {% endif %}">
                    <a class="nav-link" href="{% url 'Studentportalen:index' %}">Hjem{% if request.path == url %}<span class="sr-only">(current)</span>{% endif %}</a>
                </li>

                <li class="nav-item {% if request.path == '/emner/' %} active {% endif %}">
                    <a class="nav-link" href="{% url 'Studentportalen:emner' %}">Emner
                        {% if request.path == url %}<span class="sr-only">(current)</span>{% endif %}</a>
                </li>
            </ul>
        <!--
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="f.eks DAT100">
                <button class="btn btn-outline-success my-2 my-sm-0 sokKnapp" type="submit">Søk</button>
            </form>
            -->
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown" id="navLeftItem">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" id="drop-menu">
                        <a class="dropdown-item" href="#">Min Profil</a>
                        <a class="dropdown-item" href="#">Anmeldelser</a>
                        <a class="dropdown-item" href="#">Kommentarer </a>
                        <a class="dropdown-item" href="#"> </a>
                        <a class="dropdown-item" href="{% url 'Studentportalen:logout_user' %}">Logg ut</a>
                    </div>
                </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{% url 'Studentportalen:registrering' %}">
                            <button class="btn btn-outline-success my-2 my-sm-0 sokKnapp">Registrer bruker</button>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'Studentportalen:login_user' %}">
                            <button class="btn btn-outline-success my-2 my-sm-0 sokKnapp">Logg inn</button>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- NAVBAR SLUTT -->

    <!-- HOVEDSIDE START -->

<div class="container-fluid" id="pageContainer">
    {% block body %}

    {% endblock %}

</div>
</div>
<!--
<footer class="footer" id="footer">  -->
<!-- <nav class="navbar navbar-default navbar-fixed-bottom" role="navigation" id="footer"> -->
 <!--   <div class="row tekstFot">
        <div class="col-md-4">
            <h4>Lorem ipsum.</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, qui?</p>
        </div>
        <div class="col-md-4">
            <h4>Lorem ipsum.</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A, omnis?</p>
        </div>
        <div class="col-md-4">
            <h4>Lorem ipsum.</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, quisquam!</p>
        </div>
    </div> -->
<!-- </nav> -->
<!-- </footer> -->

<script>
    $(document).ready(function() {
        var docHeight = $(window).height();
        var footerHeight = $('#footer').height();
        var footerTop = $('#footer').position().top + footerHeight;

        if (footerTop < docHeight) {
            $('#footer').css('margin-top', 10+ (docHeight - footerTop) + 'px');
        }
    });

    $(document).ready(function() {
        var banner_height = $("#headerBilde").height();
        var lastScrollTop = 0;
        $(window).scroll(function() {
            var scroll = $(window).scrollTop();
            var currScrollTop = $(this).scrollTop();
            if (scroll >= banner_height) {
                $("#navBar").css({'background-color': 'rgba(7,54,80,1)'});
                $("#drop-menu").css({'background-color': 'rgba(7,54,80,1)'});
            } else {
                $("#navBar").css({'background-color': 'rgba(7,54,80,0.1)'});
                $("#drop-menu").css({'background-color': 'rgba(7,54,80,0.1)'});
            }
            lastScrollTop = currScrollTop;


        });

    });
</script>


<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>


</body>
</html>

Studentportalen/templates/Studentportalen/emner_django.html
{% extends 'Studentportalen/base.html' %}

{% block head_title %}Emner{% endblock %}

{% block body %}

<div id="headerContainer" class="container-fluid">
        {% load staticfiles %}
        <img title="Bildet er tatt av https://unsplash.com/@alexisrbrown" class="img-responsive" style="width: 100%" src="{% static 'bilder/IngEmneV2.png' %}" id="headerBilde">

    </div>
    </div>
    <div class="container">
        <input type="text" class="form-control" id="sokFag" onkeyup="finnFag()" placeholder="Søk etter fag..">
        <ul class="list-group" id="fagUl">
            {% for emne in emner %}
            <li class="list-group-item"><a href="{% url 'Studentportalen:fag' emne.id %}">{{ emne.navn }} - {{ emne.beskrivelse }}</a></li>
            {% endfor %}

        </ul>
    </div>
{% endblock %}

Studentportalen/templates/Studentportalen/index_django.html
{% extends 'Studentportalen/base.html' %}
{% block head_title %}Studentportalen{% endblock %}

{% block body %}

    <!-- HEADER BILDE -->
    <div id="headerContainer" class="container-fluid">
        {% load staticfiles %}
        <img title="Bildet er tatt av https://unsplash.com/@cikstefan" class="img-responsive" style="width: 100%" src="{% static 'bilder/headerForsideUtkast3.png' %}" id="headerBilde">

    </div>

    <div class="row">
        <div class="col-md-3">
            <div class="container" id="sidebar">

            <h3 id="tittelOm">Hva er Studentportalen?</h3>
                <br>
            <p>De fleste studenter ved HVL har noen valgfag. Det kan være vanskelig å bestemme seg for hvilke fag en skal
             bruke disse valgfagene på.</p>
            <p>Her på denne siden kan du finne vurderinger av de forksjellige fagene, skrevet av dine medstudenter ved HVL.</p>
            <p>På denne måten kan du være sikker på å få en ærlig vurdering av f.eks vanskelighetsgraden på de forksjellige fagene.</p>
                <br>
                <a href="{% url 'Studentportalen:emner' %}">
                    <button class="btn btn-danger btn-block btn-lg minBtnInverse">Se på alle fagene</button>
                </a>

            </div>
            </div>
        <div class="col-md-9" id="mainColIndex">
            <div class="row">
                <div class="col-md-6 text-center">
                <div class="container-fluid scoreBlob">
                    <h3>De vanskeligste fagene</h3>
                <br>
                    {% for emnet in emn_vansk %}
                        <a href="{% url 'Studentportalen:fag' emne_id=emnet.pk%}">
                            <button class="btn btn-primary minBtn">
                                {{ emnet.navn }}
                            </button>
                        </a>
                        <h5 class="score">Score: {{ emnet.vanskelig }}</h5>
                        <br>
                    {% endfor %}
                </div>
                </div>
            <div class="col-md-6 text-center">
                <div class="container-fluid scoreBlob">
                    <h3>Fagene som krever mest arbeid</h3>
                <br>
                    {% for emnet in emne_arb %}
                        <a href="{% url 'Studentportalen:fag' emne_id=emnet.pk%}">
                            <button class="btn btn-primary minBtn">
                                {{ emnet.navn }}
                            </button>
                        </a>
                        <h5 class="score">Score: {{ emnet.arbeid }}</h5>
                        <br>
                    {% endfor %}
                </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 text-center">
                <div class="container-fluid scoreBlob">
                    <h3>Fagene med flest vurderinger</h3>
                <br>
                    {% for emnet in emne_anta %}
                        <a href="{% url 'Studentportalen:fag' emne_id=emnet.pk%}">
                            <button class="btn btn-primary minBtn">
                                {{ emnet.navn }}
                            </button>
                        </a>
                        <h5 class="score">Score: {{ emnet.antall }}</h5>
                        <br>
                    {% endfor %}
                </div>
                </div>
            <div class="col-md-6 text-center">
                <div class="container-fluid scoreBlob">
                    <h3>De mest interessante fagene</h3>
                <br>
                    {% for emnet in emne_inte %}
                        <a href="{% url 'Studentportalen:fag' emne_id=emnet.pk%}">
                            <button class="btn btn-primary minBtn">
                                {{ emnet.navn }}
                            </button>
                        </a>
                        <h5 class="score">Score: {{ emnet.interesse }}</h5>
                        <br>
                    {% endfor %}
                </div>
                </div>
            </div>
        </div>
        </div>
    </div>


{% endblock %}

Studentportalen/templates/Studentportalen/logg_inn.html
{% extends 'Studentportalen/base.html' %}

{% block title %}Logg Inn{% endblock %}

{% block body %}

<div id="headerContainer" class="container-fluid">
        {% load staticfiles %}
        <img class="img-responsive" style="width: 100%" src="{% static 'bilder/headerForsideUtkast3.png' %}" id="headerBilde">

    </div>
<div class="container">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-sm-12 col-md-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Innlogging</h3>
                    {% if error_message %}
                        <p style="color: red"><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'Studentportalen:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form }}
                        <br>
                                <button type="submit" class="btn btn-success btn-block">Logg inn</button>

                    </form>
                </div>
                <div class="panel-footer">
                    Har du ikke bruker? <a href="{% url 'Studentportalen:registrering' %}">Klikk her</a> for å registrere deg.
                </div>
            </div>
        </div>
    <div class="col-md-4"></div>
    </div>

</div>

{% endblock %}

Studentportalen/templates/Studentportalen/registrering.html
{% extends 'Studentportalen/base.html' %}
{% block title %}Registrering av ny bruker{% endblock %}


{% block body %}
    <div id="headerContainer" class="container-fluid">
        {% load staticfiles %}
        <img class="img-responsive" style="width: 100%" src="{% static 'bilder/headerForsideUtkast3.png' %}" id="headerBilde">

    </div>
<div class="container">

    <div class="row">
    <div class="col-md-4"></div>
        <div class="col-sm-12 col-md-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Registrering av ny brukerkonto</h3>
                    {% if error_message %}
                        <p style="color: red"><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'Studentportalen:registrering'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form }}
                        <br>
                                <button type="submit" class="btn btn-success btn-block">Registrer ny bruker</button>

                    </form>
                </div>
                <div class="panel-footer">
                    Har en brukerkonto? <a href="{% url 'Studentportalen:login_user' %}">klikk her</a> for å logge inn.
                </div>
            </div>
        </div>
    <div class="col-md-4"></div>
    </div>

</div>

{% endblock %}